import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Category from './models/Category.model';
import Destination from './models/Destination.model';
import Tour from './models/Tour.model';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/tourify';

const categories = [
  { name: 'Adventure', description: 'Thrilling outdoor activities and expeditions', icon: 'Mountain' },
  { name: 'Nature', description: 'Explore the natural beauty of Bangladesh', icon: 'TreePine' },
  { name: 'Beach', description: 'Relax at pristine coastal destinations', icon: 'Waves' },
  { name: 'Cultural', description: 'Immerse yourself in local traditions and heritage', icon: 'Landmark' },
  { name: 'Trekking', description: 'Hike through hills, forests, and valleys', icon: 'Footprints' },
  { name: 'Wildlife', description: 'Discover diverse flora and fauna', icon: 'Bird' },
  { name: 'Spiritual', description: 'Visit sacred sites and peaceful retreats', icon: 'Heart' },
  { name: 'Luxury', description: 'Premium experiences with top-tier comfort', icon: 'Crown' },
];

const destinations = [
  { name: 'Sundarbans', description: 'The world\'s largest mangrove forest, home to the Royal Bengal Tiger', region: 'Khulna', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80' },
  { name: 'Sajek Valley', description: 'A breathtaking valley in the Chittagong Hill Tracts, known as the "Queen of Hills"', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80' },
  { name: 'Cox\'s Bazar', description: 'The world\'s longest natural sandy beach stretching 120 km', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80' },
  { name: 'Bandarban', description: 'Pristine hills and tribal culture in the Chittagong Hill Tracts', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80' },
  { name: 'Rangamati', description: 'A serene district known for Kaptai Lake and tribal heritage', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800&q=80' },
  { name: 'Saint Martin\'s Island', description: 'Bangladesh\'s only coral island with crystal-clear waters', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
  { name: 'Kuakata', description: 'The daughter of the sea, offering panoramic sunrise and sunset views', region: 'Barisal', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80' },
  { name: 'Sylhet', description: 'The land of green valleys, tea gardens, and spiritual shrines', region: 'Sylhet', image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80' },
  { name: 'Jaflong', description: 'A hill station and shopping destination famous for stone collection', region: 'Sylhet', image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80' },
  { name: 'Ratargul', description: 'The only freshwater swamp forest in Bangladesh', region: 'Sylhet', image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80' },
  { name: 'Madhabkunda', description: 'One of the largest waterfalls in Bangladesh surrounded by lush forest', region: 'Sylhet', image: 'https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=800&q=80' },
  { name: 'Lawachara', description: 'A national park famous for tropical trees and hoolock gibbons', region: 'Sylhet', image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80' },
  { name: 'Teknaf', description: 'The southeastern tip of Bangladesh with hills meeting the sea', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80' },
  { name: 'Nafakhum', description: 'The largest waterfall in Bangladesh, deep in the remote hills', region: 'Chittagong', image: 'https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=800&q=80' },
];

// Helper: create a unique admin user ID for the createdBy field
const adminUserId = new mongoose.Types.ObjectId();

const tours = [
  // --- ADVENTURE ---
  {
    title: 'Sundarbans Mangrove Explorer',
    description: 'Embark on a 3-day adventure through the world\'s largest mangrove forest. Navigate the winding waterways by boat, spot the elusive Royal Bengal Tiger, and witness crocodiles basking in the sun. This guided tour takes you deep into the heart of the Sundarbans, where you\'ll camp under the stars and learn about the unique ecosystem that supports both wildlife and local communities. Includes boat transfers, guided walks, and traditional Bengali meals.',
    shortDescription: '3-day boat safari through the Sundarbans with wildlife spotting and mangrove exploration.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    price: 15000,
    discountPrice: 12500,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 15,
    difficulty: 'moderate',
    highlights: ['Boat safari through mangrove waterways', 'Wildlife spotting including deer and crocodiles', 'Guided forest walks', 'Camping under the stars', 'Traditional Bengali cuisine'],
    included: ['All boat transfers', 'Accommodation in eco-lodge', '3 meals per day', 'Professional guide', 'Park entry fees'],
    excluded: ['Travel to Mongla', 'Personal expenses', 'Travel insurance', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Mongla Jetty',
    endPoint: 'Mongla Jetty',
    startDates: [new Date('2026-08-15'), new Date('2026-09-01'), new Date('2026-09-15')],
    category: 'Adventure',
    destination: 'Sundarbans',
    ratings: { average: 4.8, count: 124 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Bandarban Hill Tracts Expedition',
    description: 'A 4-day deep dive into the Chittagong Hill Tracts. Trek through rolling green hills, visit remote tribal villages, and learn about the Marma, Tripura, and Mro communities. The journey takes you through bamboo forests, past terraced rice paddies, and up to panoramic viewpoints. Experience authentic tribal hospitality, taste local cuisine, and witness traditional handicraft-making. This tour is perfect for those seeking cultural immersion and adventure.',
    shortDescription: '4-day cultural immersion trekking through the Chittagong Hill Tracts.',
    thumbnail: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    price: 18000,
    duration: { days: 4, nights: 3 },
    maxGroupSize: 10,
    difficulty: 'moderate',
    highlights: ['Trek to Boga Lake', 'Visit tribal villages', 'Panoramic hill views', 'Cultural performances', 'Bamboo forest walks'],
    included: ['All accommodation', 'Meals during trek', 'Local guide', 'Transport from Chittagong', 'Village entry fees'],
    excluded: ['Flights to Chittagong', 'Personal gear', 'Travel insurance', 'Tips'],
    departureLocation: 'Chittagong',
    startPoint: 'Chittagong Bus Terminal',
    endPoint: 'Chittagong Bus Terminal',
    startDates: [new Date('2026-08-20'), new Date('2026-09-10'), new Date('2026-10-01')],
    category: 'Adventure',
    destination: 'Bandarban',
    ratings: { average: 4.9, count: 67 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Nafakhum Waterfall Trek',
    description: 'Journey to the largest waterfall in Bangladesh on this 2-day trekking adventure. Starting from Thanchi, you\'ll hike through dense tropical forest, cross suspension bridges over rushing rivers, and finally arrive at the spectacular Nafakhum waterfall. The trek passes through remote villages where you can interact with local communities. Overnight camping near the waterfall with a bonfire under the stars.',
    shortDescription: '2-day trek to Bangladesh\'s largest waterfall through remote forest trails.',
    thumbnail: 'https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=1200&q=80'],
    price: 8500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 12,
    difficulty: 'challenging',
    highlights: ['Trek to Nafakhum waterfall', 'Suspension bridge crossings', 'River hiking', 'Overnight camping', 'Village interaction'],
    included: ['Camping equipment', 'Meals during trek', 'Local guide', 'Transport from Thanchi'],
    excluded: ['Transport to Thanchi', 'Personal gear', 'Travel insurance'],
    departureLocation: 'Chittagong',
    startPoint: 'Thanchi Bazaar',
    endPoint: 'Thanchi Bazaar',
    startDates: [new Date('2026-08-25'), new Date('2026-09-15')],
    category: 'Adventure',
    destination: 'Nafakhum',
    ratings: { average: 4.7, count: 45 },
    isFeatured: false,
    isActive: true,
  },
  // --- NATURE ---
  {
    title: 'Sajek Valley Sunrise Trek',
    description: 'Witness the magical sunrise above the clouds in Sajek Valley, the crown jewel of the Chittagong Hill Tracts. This 2-day tour takes you through winding mountain roads to the valley perched at 1,800 feet. Watch the sunrise paint the sky in hues of orange and gold as clouds drift below you. Visit the_HELIPAD viewpoint, trek to nearby waterfalls, and enjoy the cool mountain air. Stay in a cozy cottage with panoramic valley views.',
    shortDescription: '2-day trek to the majestic Sajek Valley for a legendary cloud-top sunrise.',
    thumbnail: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=80'],
    price: 8500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 12,
    difficulty: 'easy',
    highlights: ['Sunrise above the clouds', 'Helipad viewpoint', 'Mountain road journey', 'Valley trekking', 'Cottage stay'],
    included: ['Cottage accommodation', 'All meals', 'Transport from Khagrachhari', 'Guide fees'],
    excluded: ['Transport to Khagrachhari', 'Personal expenses', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Khagrachhari Bus Terminal',
    endPoint: 'Khagrachhari Bus Terminal',
    startDates: [new Date('2026-08-10'), new Date('2026-09-05'), new Date('2026-09-20')],
    category: 'Nature',
    destination: 'Sajek Valley',
    ratings: { average: 4.9, count: 89 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Ratargul Freshwater Swamp Adventure',
    description: 'Explore the only freshwater swamp forest in Bangladesh on this 2-day nature tour. Glide through the flooded forest by boat, spotting rare birds and aquatic life. Ratargul is home to over 200 species of birds, making it a birdwatcher\'s paradise. Visit during the monsoon season when the forest is at its most spectacular, with trees rising directly from the water. Includes boat tours, guided nature walks, and a visit to nearby Lawachara National Park.',
    shortDescription: '2-day boat tour through Bangladesh\'s only freshwater swamp forest.',
    thumbnail: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80'],
    price: 7500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 10,
    difficulty: 'easy',
    highlights: ['Boat tour through swamp forest', 'Birdwatching (200+ species)', 'Lawachara National Park visit', 'Sunrise boat ride', 'Nature photography'],
    included: ['Boat tours', 'Accommodation', 'All meals', 'Guide', 'Park entry fees'],
    excluded: ['Transport to Sylhet', 'Personal expenses', 'Tips'],
    departureLocation: 'Sylhet',
    startPoint: 'Sylhet City',
    endPoint: 'Sylhet City',
    startDates: [new Date('2026-07-20'), new Date('2026-08-05'), new Date('2026-08-20')],
    category: 'Nature',
    destination: 'Ratargul',
    ratings: { average: 4.6, count: 52 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Jaflong Stone Collection & River Tour',
    description: 'Visit Jaflong, a picturesque hill station and river delta where stones are collected from the mountains of Meghalaya. This 2-day tour combines scenic beauty with cultural exploration. Take a boat ride on the Piain River, watch workers collect stones from the riverbed, and visit the zero-point border area. The surrounding hills offer stunning views, especially during sunrise. Includes a visit to the nearby Lakkatura tea estate.',
    shortDescription: '2-day visit to Jaflong\'s stone collection river delta and tea gardens.',
    thumbnail: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80'],
    price: 6500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Piain River boat ride', 'Stone collection site visit', 'Zero point border area', 'Tea garden tour', 'Mountain views'],
    included: ['Boat ride', 'Accommodation', 'All meals', 'Local guide', 'Tea estate visit'],
    excluded: ['Transport to Sylhet', 'Personal expenses'],
    departureLocation: 'Sylhet',
    startPoint: 'Sylhet City',
    endPoint: 'Sylhet City',
    startDates: [new Date('2026-07-25'), new Date('2026-08-10'), new Date('2026-08-25')],
    category: 'Nature',
    destination: 'Jaflong',
    ratings: { average: 4.5, count: 78 },
    isFeatured: false,
    isActive: true,
  },
  // --- BEACH ---
  {
    title: 'Cox\'s Bazar Beach Retreat',
    description: 'Relax at the world\'s longest natural sandy beach on this 3-day coastal getaway. Enjoy sunrise and sunset walks along the 120 km shoreline, try exciting water sports like jet skiing and parasailing, and explore the vibrant local seafood market. Visit the Himchari waterfall and panoramic viewpoints. Stay at a beachfront resort with direct beach access. Perfect for families and couples seeking sun, sand, and relaxation.',
    shortDescription: '3-day beach vacation with water sports and coastal exploration.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
    price: 10000,
    discountPrice: 8500,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 20,
    difficulty: 'easy',
    highlights: ['Beachfront resort stay', 'Sunrise and sunset walks', 'Water sports activities', 'Himchari waterfall visit', 'Seafood market tour'],
    included: ['Resort accommodation', 'Breakfast and dinner', 'Airport transfers', 'Himchari excursion', 'Water sports discount'],
    excluded: ['Flights', 'Lunch', 'Water sports fees', 'Personal expenses'],
    departureLocation: 'Dhaka',
    startPoint: 'Cox\'s Bazar Airport',
    endPoint: 'Cox\'s Bazar Airport',
    startDates: [new Date('2026-08-01'), new Date('2026-08-15'), new Date('2026-09-01'), new Date('2026-09-15')],
    category: 'Beach',
    destination: 'Cox\'s Bazar',
    ratings: { average: 4.7, count: 156 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Saint Martin\'s Island Paradise',
    description: 'Escape to Bangladesh\'s only coral island on this 3-day island adventure. Saint Martin\'s offers crystal-clear waters, vibrant coral reefs, and pristine beaches far from the mainland crowds. Snorkel among colorful fish, explore the island by bicycle, and enjoy the famous coconut groves. Visit Chera Dwip at low tide for a walk on the coral beach. Stay in a cozy cottage with ocean views and feast on the island\'s legendary lobster dinner.',
    shortDescription: '3-day island getaway to Bangladesh\'s only coral island with snorkeling.',
    thumbnail: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80'],
    price: 12000,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Snorkeling in coral reefs', 'Chera Dwip coral beach walk', 'Bicycle island tour', 'Lobster dinner', 'Sunset at coconut grove'],
    included: ['Cottage accommodation', 'All meals', 'Speedboat transfer', 'Snorkeling gear', 'Island tour guide'],
    excluded: ['Transport to Teknaf', 'Personal expenses', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Teknaf Jetty',
    endPoint: 'Teknaf Jetty',
    startDates: [new Date('2026-09-01'), new Date('2026-09-15'), new Date('2026-10-01')],
    category: 'Beach',
    destination: 'Saint Martin\'s Island',
    ratings: { average: 4.8, count: 98 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Kuakata Sunrise & Sunset Experience',
    description: 'Visit Kuakata, the only place in Bangladesh where you can see both sunrise and sunset over the Bay of Bengal. This 2-day tour takes you to the southernmost tip of the country, where the beach stretches 18 km. Watch the sunrise paint the sky in shades of pink, then explore the Rakhine tribal village and visit the centuries-old Kuakata well. The seafood here is legendary — try the fresh crab and shrimp. Perfect for photographers and nature lovers.',
    shortDescription: '2-day trip to the only beach where you can see both sunrise and sunset.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
    price: 7000,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Sunrise and sunset viewing', 'Rakhine tribal village', 'Kuakata ancient well', 'Seafood feast', 'Beach camping'],
    included: ['Beach cottage', 'All meals', 'Transport from Barisal', 'Local guide', 'Boat ride'],
    excluded: ['Transport to Barisal', 'Personal expenses'],
    departureLocation: 'Barisal',
    startPoint: 'Barisal Bus Terminal',
    endPoint: 'Barisal Bus Terminal',
    startDates: [new Date('2026-08-05'), new Date('2026-08-20'), new Date('2026-09-05')],
    category: 'Beach',
    destination: 'Kuakata',
    ratings: { average: 4.6, count: 63 },
    isFeatured: false,
    isActive: true,
  },
  // --- CULTURAL ---
  {
    title: 'Rangamati Lake & Tribal Heritage Tour',
    description: 'Explore Rangamati, the "Lake City" of Bangladesh, on this 3-day cultural journey. Cruise on Kaptai Lake, the largest artificial lake in the country, surrounded by lush green hills. Visit the Tribal Cultural Museum, Rajbongshi Heritage Village, and the iconic Hanging Bridge. Interact with Chakma and Marma communities, learn about their weaving traditions, and purchase authentic handicrafts. The natural beauty combined with rich cultural heritage makes this tour unforgettable.',
    shortDescription: '3-day cultural tour of Kaptai Lake and tribal heritage sites.',
    thumbnail: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1200&q=80'],
    price: 11000,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Kaptai Lake cruise', 'Tribal Cultural Museum', 'Hanging Bridge visit', 'Tribal village tour', 'Handicraft shopping'],
    included: ['Hotel accommodation', 'All meals', 'Lake cruise', 'Museum entry', 'Guide'],
    excluded: ['Transport to Rangamati', 'Personal expenses', 'Tips'],
    departureLocation: 'Chittagong',
    startPoint: 'Rangamati Bus Terminal',
    endPoint: 'Rangamati Bus Terminal',
    startDates: [new Date('2026-08-10'), new Date('2026-09-01'), new Date('2026-09-20')],
    category: 'Cultural',
    destination: 'Rangamati',
    ratings: { average: 4.7, count: 71 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Sylhet Tea Garden & Shrine Trail',
    description: 'Discover Sylhet, the spiritual heartland of Bangladesh. Visit the iconic Shah Jalal Shrine, surrounded by thousands of pigeons, and the adjacent Shah Amanat Shrine. Drive through rolling green tea gardens, stopping at a tea factory to learn the processing journey from leaf to cup. Visit the Hakaluki Haor, one of the largest freshwater wetlands in Asia, and enjoy a boat ride at sunset. The tour includes Sylhet\'s best biryani at a local restaurant.',
    shortDescription: '3-day spiritual and scenic tour of Sylhet\'s shrines and tea gardens.',
    thumbnail: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&q=80'],
    price: 9500,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Shah Jalal Shrine visit', 'Tea garden drive', 'Tea factory tour', 'Hakaluki Haor boat ride', 'Sylheti cuisine'],
    included: ['Hotel accommodation', 'All meals', 'All transport', 'Guide', 'Tea factory entry'],
    excluded: ['Flights to Sylhet', 'Personal expenses', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Osmani Airport, Sylhet',
    endPoint: 'Osmani Airport, Sylhet',
    startDates: [new Date('2026-08-01'), new Date('2026-08-15'), new Date('2026-09-01')],
    category: 'Cultural',
    destination: 'Sylhet',
    ratings: { average: 4.8, count: 93 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Madhabkunda Waterfall & Sylhet Nature Trail',
    description: 'Visit Madhabkunda, one of the largest waterfalls in Bangladesh, on this 2-day nature and cultural tour. The 200-foot waterfall cascades into a pool surrounded by lush forest and rocky terrain. Trek through the nature trail to the viewpoint, swim in the natural pool, and explore the nearby Madhabkunda Eco Park. The tour also includes a visit to a local tea garden and the scenic Bichanakandi river with its crystal-clear water and stone-filled bed.',
    shortDescription: '2-day trip to Madhabkunda waterfall and Bichanakandi river.',
    thumbnail: 'https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1432405972618-c6b0cfba8b41?w=1200&q=80'],
    price: 7000,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Madhabkunda waterfall trek', 'Natural pool swimming', 'Bichanakandi river visit', 'Tea garden tour', 'Eco park exploration'],
    included: ['Accommodation', 'All meals', 'Transport from Sylhet', 'Guide', 'Entry fees'],
    excluded: ['Transport to Sylhet', 'Personal expenses'],
    departureLocation: 'Sylhet',
    startPoint: 'Sylhet City',
    endPoint: 'Sylhet City',
    startDates: [new Date('2026-07-15'), new Date('2026-08-01'), new Date('2026-08-15')],
    category: 'Cultural',
    destination: 'Madhabkunda',
    ratings: { average: 4.6, count: 58 },
    isFeatured: false,
    isActive: true,
  },
  // --- TREKKING ---
  {
    title: 'Keokradong Summit Trek',
    description: 'Conquer Keokradong, one of the highest peaks in Bangladesh at 1,230 meters, on this challenging 3-day trek. Starting from Thanchi, the trail passes through dense tropical forests, crosses suspension bridges, and climbs steep hillsides. The summit offers breathtaking panoramic views of the surrounding hills and Myanmar border. Camp overnight at the base camp with a bonfire and stargazing. This trek is for adventurous souls seeking Bangladesh\'s most dramatic mountain experience.',
    shortDescription: '3-day challenging trek to Bangladesh\'s highest accessible peak.',
    thumbnail: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    price: 14000,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 8,
    difficulty: 'challenging',
    highlights: ['Summit at 1,230m', 'Panoramic mountain views', 'Jungle trail trekking', 'Campfire and stargazing', 'Suspension bridge crossings'],
    included: ['Camping equipment', 'All meals during trek', 'Professional trekking guide', 'Porters', 'Thanchi transport'],
    excluded: ['Transport to Thanchi', 'Personal trekking gear', 'Travel insurance'],
    departureLocation: 'Chittagong',
    startPoint: 'Thanchi Bazaar',
    endPoint: 'Thanchi Bazaar',
    startDates: [new Date('2026-10-01'), new Date('2026-10-15'), new Date('2026-11-01')],
    category: 'Trekking',
    destination: 'Bandarban',
    ratings: { average: 4.9, count: 34 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Sajek to Rangamati Hill Trek',
    description: 'A scenic 4-day trek connecting two iconic hill destinations. Starting from Sajek Valley, the trail winds through remote villages, bamboo forests, and hill ridges with stunning valley views. You\'ll stay in tribal homestays, eat local food, and experience genuine hospitality far from tourist crowds. The trek ends at Rangamati, where you can celebrate with a boat ride on Kaptai Lake. This trek offers a perfect blend of nature, culture, and adventure.',
    shortDescription: '4-day trek from Sajek Valley to Rangamati through tribal villages.',
    thumbnail: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=80'],
    price: 16000,
    duration: { days: 4, nights: 3 },
    maxGroupSize: 10,
    difficulty: 'moderate',
    highlights: ['Sajek to Rangamati trail', 'Tribal homestays', 'Bamboo forest trekking', 'Valley viewpoints', 'Kaptai Lake celebration'],
    included: ['Homestay accommodation', 'All meals', 'Professional guide', 'Porters', 'Kaptai Lake boat ride'],
    excluded: ['Transport to Sajek', 'Personal gear', 'Travel insurance'],
    departureLocation: 'Chittagong',
    startPoint: 'Sajek Valley',
    endPoint: 'Rangamati',
    startDates: [new Date('2026-10-05'), new Date('2026-10-20')],
    category: 'Trekking',
    destination: 'Sajek Valley',
    ratings: { average: 4.8, count: 28 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Lawachara National Park Trail',
    description: 'Explore Lawachara National Park, one of the most important protected areas in Bangladesh. This 2-day tour takes you through semi-evergreen tropical forests, home to the endangered hoolock gibbon, along with 250+ bird species. Walk the well-marked nature trails, visit the tea plantation border, and explore the nearby stone quarries. Stay in a forest rest house and wake to the sound of gibbons calling. The park is also famous for its century-old tea plants.',
    shortDescription: '2-day nature trail through Lawachara National Park with wildlife spotting.',
    thumbnail: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80'],
    price: 6500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 12,
    difficulty: 'easy',
    highlights: ['Hoolock gibbon spotting', 'Nature trail walks', 'Tea plantation visit', 'Bird watching (250+ species)', 'Forest rest house stay'],
    included: ['Forest rest house', 'All meals', 'Park entry fees', 'Nature guide', 'Transport from Srimangal'],
    excluded: ['Transport to Srimangal', 'Personal expenses'],
    departureLocation: 'Sylhet',
    startPoint: 'Srimangal',
    endPoint: 'Srimangal',
    startDates: [new Date('2026-07-20'), new Date('2026-08-05'), new Date('2026-08-20')],
    category: 'Trekking',
    destination: 'Lawachara',
    ratings: { average: 4.7, count: 41 },
    isFeatured: false,
    isActive: true,
  },
  // --- WILDLIFE ---
  {
    title: 'Sundarbans Wildlife Safari',
    description: 'A specialized 4-day wildlife-focused tour through the Sundarbans, designed for serious nature enthusiasts. Unlike standard tours, this expedition uses experienced wildlife trackers and spotlights for night safaris. Focus on tracking the Royal Bengal Tiger, saltwater crocodiles, Ganges river dolphins, and the diverse birdlife of the mangroves. Includes multiple boat routes through different zones of the forest and overnight stays at forest rest houses.',
    shortDescription: '4-day expert-guided wildlife safari in the Sundarbans with night tracking.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    price: 25000,
    duration: { days: 4, nights: 3 },
    maxGroupSize: 8,
    difficulty: 'moderate',
    highlights: ['Expert wildlife tracker', 'Night safari with spotlights', 'Tiger tracking', 'River dolphin spotting', 'Multiple forest zones'],
    included: ['Forest rest house', 'All meals', 'Expert tracker', 'All boat transfers', 'Park permits'],
    excluded: ['Transport to Mongla', 'Binoculars', 'Travel insurance', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Mongla Jetty',
    endPoint: 'Mongla Jetty',
    startDates: [new Date('2026-11-01'), new Date('2026-11-15'), new Date('2026-12-01')],
    category: 'Wildlife',
    destination: 'Sundarbans',
    ratings: { average: 4.9, count: 42 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Teknaf Mangrove & Birdwatching Tour',
    description: 'Explore the Teknaf Peninsula, the southeasternmost point of Bangladesh, on this 2-day wildlife tour. The area is home to the Teknaf Wildlife Sanctuary, one of the most important bird habitats in the country. Spot migratory birds from Siberia, observe wild elephants, and explore the mangrove ecosystem. The tour includes a boat ride along the Naf River to the Myanmar border, where you can see the contrasting landscapes of the two countries.',
    shortDescription: '2-day birdwatching and wildlife tour at Teknaf Peninsula.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    price: 8000,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 10,
    difficulty: 'easy',
    highlights: ['Birdwatching sanctuary visit', 'Wild elephant spotting', 'Naf River boat ride', 'Mangrove exploration', 'Myanmar border view'],
    included: ['Accommodation', 'All meals', 'Boat ride', 'Guide', 'Sanctuary entry'],
    excluded: ['Transport to Cox\'s Bazar', 'Personal expenses'],
    departureLocation: 'Cox\'s Bazar',
    startPoint: 'Cox\'s Bazar',
    endPoint: 'Cox\'s Bazar',
    startDates: [new Date('2026-12-01'), new Date('2026-12-15'), new Date('2027-01-01')],
    category: 'Wildlife',
    destination: 'Teknaf',
    ratings: { average: 4.6, count: 35 },
    isFeatured: false,
    isActive: true,
  },
  // --- SPIRITUAL ---
  {
    title: 'Bagerhat Islamic Heritage Tour',
    description: 'Visit the UNESCO World Heritage city of Bagerhat on this 2-day spiritual and historical journey. Explore the Sixty Dome Mosque (Shat Gombuj Masjid), the largest medieval mosque in Bangladesh, and the tomb of Khan Jahan Ali. Wander through the medieval city ruins, visit the Nine Dome Mosque, and explore the historic tank (dighi). Bagerhat offers a fascinating glimpse into the Sultanate period of Bengal and is a must-visit for history and architecture enthusiasts.',
    shortDescription: '2-day heritage tour of Bagerhat\'s UNESCO World Heritage mosques.',
    thumbnail: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?w=1200&q=80'],
    price: 6000,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 15,
    difficulty: 'easy',
    highlights: ['Sixty Dome Mosque visit', 'Khan Jahan Ali tomb', 'Medieval city ruins', 'Nine Dome Mosque', 'Historic dighi exploration'],
    included: ['Hotel accommodation', 'All meals', 'Heritage guide', 'Transport from Khulna', 'Entry fees'],
    excluded: ['Transport to Khulna', 'Personal expenses'],
    departureLocation: 'Khulna',
    startPoint: 'Khulna Bus Terminal',
    endPoint: 'Khulna Bus Terminal',
    startDates: [new Date('2026-08-10'), new Date('2026-09-01'), new Date('2026-09-20')],
    category: 'Spiritual',
    destination: 'Sundarbans',
    ratings: { average: 4.7, count: 48 },
    isFeatured: false,
    isActive: true,
  },
  {
    title: 'Lalakhal River & Neermahal Palace Tour',
    description: 'Discover the hidden gem of Sylhet on this 2-day tour. Lalakhal is a stunning river with crystal-clear blue water surrounded by green hills — a rare sight in Bangladesh. Take a boat ride on the river, swim in the clear waters, and visit the royal Neermahal (Water Palace) built by the Tripura king in the middle of a lake. The palace is a blend of Hindu and Mughal architecture. End the day with a traditional Sylheti dinner at a local restaurant.',
    shortDescription: '2-day tour of Lalakhal\'s crystal river and Neermahal Water Palace.',
    thumbnail: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1200&q=80'],
    price: 7500,
    duration: { days: 2, nights: 1 },
    maxGroupSize: 12,
    difficulty: 'easy',
    highlights: ['Lalakhal crystal river boat ride', 'Neermahal Water Palace visit', 'Swimming in clear water', 'Hill and river views', 'Sylheti cuisine dinner'],
    included: ['Accommodation', 'All meals', 'Boat ride', 'Palace entry', 'Guide'],
    excluded: ['Transport to Sylhet', 'Personal expenses'],
    departureLocation: 'Sylhet',
    startPoint: 'Sylhet City',
    endPoint: 'Sylhet City',
    startDates: [new Date('2026-08-01'), new Date('2026-08-15'), new Date('2026-09-01')],
    category: 'Spiritual',
    destination: 'Sylhet',
    ratings: { average: 4.8, count: 55 },
    isFeatured: false,
    isActive: true,
  },
  // --- LUXURY ---
  {
    title: 'Luxury Cox\'s Bazar Beachfront Escape',
    description: 'Indulge in a premium 4-day beachfront experience at Cox\'s Bazar. Stay at a 5-star resort with private beach access, infinity pool, and spa. Enjoy sunrise yoga sessions, gourmet dining featuring fresh seafood, and exclusive water sports like deep-sea fishing and helicopter tours. Visit the Himchari waterfall by private jeep and shop at the premium craft market. This tour is designed for those who want the best of the best.',
    shortDescription: '4-day premium beachfront resort experience with spa and exclusive activities.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
    price: 45000,
    discountPrice: 38000,
    duration: { days: 4, nights: 3 },
    maxGroupSize: 6,
    difficulty: 'easy',
    highlights: ['5-star beachfront resort', 'Private beach access', 'Infinity pool and spa', 'Sunrise yoga sessions', 'Gourmet seafood dining'],
    included: ['5-star resort accommodation', 'Breakfast and dinner', 'Airport transfers', 'Spa session', 'Himchari jeep tour'],
    excluded: ['Flights', 'Lunch', 'Premium activities', 'Personal expenses'],
    departureLocation: 'Dhaka',
    startPoint: 'Cox\'s Bazar Airport',
    endPoint: 'Cox\'s Bazar Airport',
    startDates: [new Date('2026-09-01'), new Date('2026-09-15'), new Date('2026-10-01')],
    category: 'Luxury',
    destination: 'Cox\'s Bazar',
    ratings: { average: 4.9, count: 31 },
    isFeatured: true,
    isActive: true,
  },
  {
    title: 'Sundarbans Luxury River Cruise',
    description: 'Experience the Sundarbans in ultimate comfort on this 3-day luxury river cruise aboard a private houseboat. Glide through the mangrove waterways in a fully air-conditioned vessel with a private chef, personalized itinerary, and expert naturalist guide. Spot tigers, crocodiles, and exotic birds from the deck while enjoying gourmet meals. Evening cultural performances on the boat and guided night walks complete this premium wilderness experience.',
    shortDescription: '3-day luxury houseboat cruise through the Sundarbans with gourmet dining.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    price: 35000,
    duration: { days: 3, nights: 2 },
    maxGroupSize: 6,
    difficulty: 'easy',
    highlights: ['Private luxury houseboat', 'Personal chef and butler', 'Expert naturalist guide', 'Gourmet Bengali cuisine', 'Cultural performances'],
    included: ['Houseboat accommodation', 'All gourmet meals', 'Premium beverages', 'Expert guide', 'All activities'],
    excluded: ['Transport to Mongla', 'Premium alcohol', 'Tips'],
    departureLocation: 'Dhaka',
    startPoint: 'Mongla Jetty',
    endPoint: 'Mongla Jetty',
    startDates: [new Date('2026-10-01'), new Date('2026-10-15'), new Date('2026-11-01')],
    category: 'Luxury',
    destination: 'Sundarbans',
    ratings: { average: 5.0, count: 18 },
    isFeatured: false,
    isActive: true,
  },
];

async function seed() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB.\n');

    // Clear existing data
    console.log('Clearing existing data...');
    await Category.deleteMany({});
    await Destination.deleteMany({});
    await Tour.deleteMany({});
    console.log('Data cleared.\n');

    // Create categories
    console.log('Seeding categories...');
    const createdCategories = await Category.insertMany(
      categories.map((c) => ({ ...c, slug: c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }))
    );
    const categoryMap = new Map(createdCategories.map((c) => [c.name, c._id]));
    console.log(`Created ${createdCategories.length} categories.\n`);

    // Create destinations
    console.log('Seeding destinations...');
    const createdDestinations = await Destination.insertMany(
      destinations.map((d) => ({ ...d, slug: d.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') }))
    );
    const destinationMap = new Map(createdDestinations.map((d) => [d.name, d._id]));
    console.log(`Created ${createdDestinations.length} destinations.\n`);

    // Create tours
    console.log('Seeding tours...');
    const tourDocs = tours.map((t) => {
      const { category, destination, ...rest } = t;
      return {
        ...rest,
        category: categoryMap.get(category),
        destination: destinationMap.get(destination),
        createdBy: adminUserId,
      };
    });
    const createdTours = await Tour.insertMany(tourDocs);
    console.log(`Created ${createdTours.length} tours.\n`);

    console.log('Seed completed successfully!');
    console.log(`  Categories: ${createdCategories.length}`);
    console.log(`  Destinations: ${createdDestinations.length}`);
    console.log(`  Tours: ${createdTours.length}`);
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();